### ISSUE TITLE
2장. 객체 생성과 파괴 (Item 1~9)

### ISSUE THREAD

**Issue by alanhakhyeonsong** [Next-Level-Study/effective-java-study#1]
- 일요일 스터디 시간 전까지 Item 1~9를 읽고, 이해가 안가거나 궁금한 것, 같이 이야기 해 볼 내용이 있다면 댓글로 아래와 같이 남겨주시면 됩니다.

ex)
```
Item 1. 생성자 대신 정적 팩터리 메서드를 고려하라

9p 중 ~~~한 이야기가 있는데 이게 잘 와닿지 않습니다.
```

- 답변은 아무나 자유롭게 댓글로 mention 을 활용해서 남겨주셔도 되고 본 스터디 시간에 해당 Q&A를 활용하고자 합니다.

**Comment by alanhakhyeonsong** [comment]
이번 챕터 주제가 `객체의 생성 및 파괴`라서 조금 어렵겠지만... Java의 Runtime Data Area와 GC의 원리에 대해서 한번 쯤은 꼭 찾아보시면 좋겠습니다.

**Comment by JeongJaew0n** [comment]
8장이 예제가 너무 어렵습니다..
finalizer와 cleaner 사용해 보신분 있으신가요?

**Comment by Kurmarkpzgr** [comment]
33페이지의 KeySet의  Set view가 뭔지 잘 모르겠습니다. 아시는분 계실까요?

**Comment by alanhakhyeonsong** [comment]
@Kurmarkpzgr `HashMap` 계열에서 Key만을 뽑아내는 `KeySet`이 어떻게 뽑히는지 내부를 보면 아실 수 있습니다.

<img width="778" alt="image" src="https://github.com/Next-Level-Study/effective-java-study/assets/60968342/bafbea7c-e726-4797-b4b2-adf6b893eecd">

**Comment by alanhakhyeonsong** [comment]
@JeongJaew0n 
1. Object에 있는 `finalizer()`는 Java 9부터 Deprecated 됐기 때문에 비교적 최신 Java로 언어 사용을 시작했다면 활용하는 예제는 보지 못했을 겁니다. 또한 `java.lang.ref` 내의 `Cleaner` 클래스를 살펴보세요.
2. 뭐... 그럴거 같네요? 극단적으로 특별한 케이스가 아니면 JVM을 믿어야겠지요...?
