### ISSUE TITLE
5장. 제네릭 (item 26~29)

### ISSUE THREAD

**Issue by alanhakhyeonsong** [Next-Level-Study/effective-java-study#17]
- 일요일 스터디 시간 전까지 Item 26~29를 읽고, 이해가 안가거나 궁금한 것, 같이 이야기 해 볼 내용이 있다면 댓글로 아래와 같이 남겨주시면 됩니다.

ex)
```
Item 1. 생성자 대신 정적 팩터리 메서드를 고려하라

9p 중 ~~~한 이야기가 있는데 이게 잘 와닿지 않습니다.
```

- 답변은 아무나 자유롭게 댓글로 mention 을 활용해서 남겨주셔도 됩니다.
- 본 스터디 시간에 해당 Q&A를 활용하고자 합니다.

**Comment by alanhakhyeonsong** [comment]
바로 대답할 수 있어야 하는 질문
- 제네릭 배열을 생성할 수 없는 이유는??
- 제네릭 타입이 다른 것만으로 메서드 오버로딩이 가능한가??

**Comment by alanhakhyeonsong** [comment]
2번이 무슨말이냐??

```java
void method1(Test<Animal> testAnimal) {};
void method1(Test<Dog> testDog) {};
```

이게 가능한가? 그렇지 않다면 왜 불가한가??

**Comment by SuJeong68** [comment]
1. E[] arr = new E[]; 면 런타임 시 원소의 타입 정보가 소거되기 때문
2. ??
